update githuv actions

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,3 +1,58 @@
+# name: Playwright Tests
+# on:
+#   push:
+#     branches: [ main, master ]
+#   pull_request:
+#     branches: [ main, master ]
+# jobs:
+#   test:
+#     timeout-minutes: 60
+#     runs-on: ubuntu-latest
+#     steps:
+#     - uses: actions/checkout@v4
+#     - uses: actions/setup-node@v4
+#       with:
+#         node-version: lts/*
+#     - name: Install dependencies
+#       run: npm ci
+#     - name: Install Playwright Browsers
+#       run: npx playwright install --with-deps
+#     - name: Run Playwright tests
+#       run: npx playwright test
+#     - uses: actions/upload-artifact@v4
+#       if: ${{ !cancelled() }}
+#       with:
+#         name: playwright-report
+#         path: playwright-report/
+#         retention-days: 30
+#     - name: Wait for playwright-report and upload if present
+#       if: ${{ always() }}
+#       shell: bash
+#       run: |
+#         REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
+#         RETRIES=5
+#         DELAY=10 # seconds
+
+#         for i in $(seq 1 $RETRIES); do
+#           if [ "$(ls -A ./playwright-report)" ]; then
+#             azcopy cp --recursive "./playwright-report" "https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/\$web/$REPORT_DIR"
+#             echo "::notice title=HTML report url::https://<STORAGE_ACCOUNT_NAME>.z1.web.core.windows.net/$REPORT_DIR/index.html"
+#             exit 0
+#           else
+#             echo "No files found in ./playwright-report. Attempt $i/$RETRIES. Waiting $DELAY seconds..."
+#             sleep $DELAY
+#           fi
+#         done
+
+#         echo "No files found in ./playwright-report after $RETRIES attempts. Skipping azcopy."
+#         exit 1
+#       env:
+#         AZCOPY_AUTO_LOGIN_TYPE: SPN
+#         AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
+#         AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
+#         AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'
+
+
 name: Playwright Tests
 on:
   push:
@@ -9,8 +64,8 @@ jobs:
     timeout-minutes: 60
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
+    - uses: actions/checkout@v5
+    - uses: actions/setup-node@v5
       with:
         node-version: lts/*
     - name: Install dependencies
@@ -25,29 +80,3 @@ jobs:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
-    - name: Wait for playwright-report and upload if present
-      if: ${{ always() }}
-      shell: bash
-      run: |
-        REPORT_DIR="run-${{ github.run_id }}-${{ github.run_attempt }}"
-        RETRIES=5
-        DELAY=10 # seconds
-
-        for i in $(seq 1 $RETRIES); do
-          if [ "$(ls -A ./playwright-report)" ]; then
-            azcopy cp --recursive "./playwright-report" "https://<STORAGE_ACCOUNT_NAME>.blob.core.windows.net/\$web/$REPORT_DIR"
-            echo "::notice title=HTML report url::https://<STORAGE_ACCOUNT_NAME>.z1.web.core.windows.net/$REPORT_DIR/index.html"
-            exit 0
-          else
-            echo "No files found in ./playwright-report. Attempt $i/$RETRIES. Waiting $DELAY seconds..."
-            sleep $DELAY
-          fi
-        done
-
-        echo "No files found in ./playwright-report after $RETRIES attempts. Skipping azcopy."
-        exit 1
-      env:
-        AZCOPY_AUTO_LOGIN_TYPE: SPN
-        AZCOPY_SPA_APPLICATION_ID: '${{ secrets.AZCOPY_SPA_APPLICATION_ID }}'
-        AZCOPY_SPA_CLIENT_SECRET: '${{ secrets.AZCOPY_SPA_CLIENT_SECRET }}'
-        AZCOPY_TENANT_ID: '${{ secrets.AZCOPY_TENANT_ID }}'
